package irt.gui.data.packet.enums;

public enum PacketType {

	SPONTANEOUS		((byte)0),		/* Spontaneous message, generated by device. */
	RESPONSE		((byte)1),		/* Response, generated as response to command or status request. */
	REQUEST			((byte)2),		/* Status request. */
	COMMAND			((byte)3),		/* Command. */
	ACKNOWLEGEMENT	((byte)0xFF);	/* Layer 2 acknowlegement. */

	private byte value; 		public byte getValue() { return value; }

	private PacketType(byte value){
		this.value = value;
	}

	@Override
	public String toString(){
		return name() + ":" + value;
	}
}
