package irt.gui.web.beans;

import java.util.Arrays;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor @Getter
public enum PacketType {

	SPONTANEOUS((byte) 0x0),					/* Spontaneous message, generated by device. */
	RESPONSE((byte) 0x1),						/* Response, generated as response to command or status request. */
	REQUEST((byte) 0x2),						/* Status request. */
	COMMAND((byte) 0x3),						/* Command. */
	ACKNOWLEDGEMENT((byte) 0xFF);	/* Layer 2 acknowledgement. */

	private final byte code;

	public static PacketType valueOf(byte b) {
		return Arrays.stream(values()).parallel().filter(pt->pt.code==b).findAny().orElse(SPONTANEOUS);
	}
}
